server.port: ${SERVER_PORT:8082}
toptuna.catalog.seedFile: ${SEED_FILE:classpath:seeds/toptuna_demo_products.csv}
toptuna.external.api.url: ${EXTERNAL_API_URL:https://api.toptuna.de/products}
toptuna.external.api.key: ${EXTERNAL_API_KEY:}
toptuna.backup.directory: ${BACKUP_DIRECTORY:./backups}
ai.provider: ${AI_PROVIDER:openai}
openai.api.key: ${OPENAI_API_KEY:}
openai.api.url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
openai.api.model: ${OPENAI_API_MODEL:gpt-4o-mini}
claude.api.key: ${CLAUDE_API_KEY:}
claude.api.url: ${CLAUDE_API_URL:https://api.anthropic.com/v1/messages}
claude.api.model: ${CLAUDE_API_MODEL:claude-3-haiku-20240307}
