# TopTuna B2B Portal - Render.com Deployment
# Fischgroßhandel für vietnamesische Restaurants

databases:
  - name: toptuna-db
    databaseName: toptuna
    user: toptuna_user
    plan: free
    postgresMajorVersion: 15
    ipAllowList: []

services:
  # Frontend - Angular 17 PWA (DE/VI/EN)
  - type: web
    name: toptuna-frontend
    env: static
    # Build: wir ersetzen vor dem Build den Platzhalter in einer template-Datei
    # (siehe src/environments/environment.prod.template.ts -> __API_BASE__)
    buildCommand: |
      cd frontend
      npm ci
      sed -i "s|__API_BASE__|https://toptuna-gateway.onrender.com/api|g" src/environments/environment.prod.template.ts || true
      mv src/environments/environment.prod.template.ts src/environments/environment.prod.ts
      npm run build:prod
    staticPublishPath: frontend/dist/toptuna-frontend
    envVars:
      - key: API_BASE
        value: https://toptuna-gateway.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff

  # Gateway - Spring Cloud Gateway + Security (Docker)
  - type: web
    name: toptuna-gateway
    env: docker
    dockerfilePath: gateway/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: toptuna-db
          property: connectionString
      - key: AUTH_URL
        value: https://toptuna-auth.onrender.com
      - key: CATALOG_URL
        value: https://toptuna-catalog.onrender.com
      - key: ORDERS_URL
        value: https://toptuna-orders.onrender.com
      - key: LOGISTICS_URL
        value: https://toptuna-logistics.onrender.com
      - key: CRM_URL
        value: https://toptuna-crm.onrender.com
      - key: EXPORT_URL
        value: https://toptuna-export.onrender.com
      - key: GATEWAY_ALLOWED_ORIGINS
        value: https://toptuna-frontend.onrender.com
      - key: JWT_SECRET
        value: "<SET_IN_RENDER_DASHBOARD:JWT_SECRET>"
    healthCheckPath: /health

  # Auth Service - JWT + Rollen (Docker)
  - type: web
    name: toptuna-auth
    env: docker
    dockerfilePath: auth-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: toptuna-db
          property: connectionString
      - key: JWT_SECRET
        value: "<SET_IN_RENDER_DASHBOARD:JWT_SECRET>"
    healthCheckPath: /health

  # Catalog Service - Produktkatalog + Staffelpreise (Docker)
  - type: web
    name: toptuna-catalog
    env: docker
    dockerfilePath: catalog-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: toptuna-db
          property: connectionString
    healthCheckPath: /health

  # Order Service - Warenkorb + Bestellmanagement (Docker)
  - type: web
    name: toptuna-orders
    env: docker
    dockerfilePath: order-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: toptuna-db
          property: connectionString
    healthCheckPath: /health

  # Logistics Service - Tour-/Lieferplanung + HACCP (Docker)
  - type: web
    name: toptuna-logistics
    env: docker
    dockerfilePath: logistics-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: toptuna-db
          property: connectionString
    healthCheckPath: /health

  # CRM Service - Kundendaten + Segmente + Kampagnen (Docker)
  - type: web
    name: toptuna-crm
    env: docker
    dockerfilePath: crm-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: toptuna-db
          property: connectionString
    healthCheckPath: /health

  # Export Service - DATEV/CSV Export (Docker)
  - type: web
    name: toptuna-export
    env: docker
    dockerfilePath: export-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: toptuna-db
          property: connectionString
    healthCheckPath: /health
