server:
  port: ${SERVER_PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_URL:http://auth:8081}
          predicates:
            - Path=/api/auth/**
        - id: catalog-service
          uri: ${CATALOG_URL:http://catalog:8082}
          predicates:
            - Path=/api/catalog/**
        - id: orders-service
          uri: ${ORDERS_URL:http://orders:8083}
          predicates:
            - Path=/api/orders/**
        - id: logistics-service
          uri: ${LOGISTICS_URL:http://logistics:8084}
          predicates:
            - Path=/api/logistics/**
        - id: crm-service
          uri: ${CRM_URL:http://crm:8085}
          predicates:
            - Path=/api/crm/**
        - id: export-service
          uri: ${EXPORT_URL:http://export:8086}
          predicates:
            - Path=/api/export/**

toptuna:
  cors:
    allowed-origins: ${GATEWAY_ALLOWED_ORIGINS:http://localhost:4200}