# ops/docker-compose.yml (angepasst)
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: ops-frontend:latest
    ports:
      - "4200:80"
    depends_on:
      - gateway
    env_file:
      - .env

  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile.maven
      args:
        SERVICE_DIR: gateway
    image: ops-gateway:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
      - SERVER_PORT=8080
      - GATEWAY_ALLOWED_ORIGINS=http://localhost:4200
      - AUTH_URL=http://auth:8081
      - CATALOG_URL=http://catalog:8082
      - ORDERS_URL=http://orders:8083
      - LOGISTICS_URL=http://logistics:8084
      - CRM_URL=http://crm:8085
      - EXPORT_URL=http://export:8086
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - JWT_REFRESH_EXPIRATION_MS=${JWT_REFRESH_EXPIRATION_MS}
    depends_on:
      - auth
      - catalog
      - orders
      - logistics
      - crm
      - export
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  auth:
    build:
      context: ..
      dockerfile: docker/Dockerfile.maven
      args:
        SERVICE_DIR: auth-service
    image: ops-auth:latest
    env_file:
      - .env
    environment:
      - SERVER_PORT=8081
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - JWT_REFRESH_EXPIRATION_MS=${JWT_REFRESH_EXPIRATION_MS}
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  catalog:
    build:
      context: ..
      dockerfile: docker/Dockerfile.maven
      args:
        SERVICE_DIR: catalog-service
    image: ops-catalog:latest
    env_file:
      - .env
    environment:
      - SERVER_PORT=8082
      - SEED_FILE=classpath:seeds/toptuna_demo_products.csv
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  orders:
    build:
      context: ..
      dockerfile: docker/Dockerfile.maven
      args:
        SERVICE_DIR: order-service
    image: ops-orders:latest
    env_file:
      - .env
    environment:
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8083/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  logistics:
    build:
      context: ..
      dockerfile: docker/Dockerfile.maven
      args:
        SERVICE_DIR: logistics-service
    image: ops-logistics:latest
    env_file:
      - .env
    environment:
      - SERVER_PORT=8084
    ports:
      - "8084:8084"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8084/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  crm:
    build:
      context: ..
      dockerfile: docker/Dockerfile.maven
      args:
        SERVICE_DIR: crm-service
    image: ops-crm:latest
    env_file:
      - .env
    environment:
      - SERVER_PORT=8085
    ports:
      - "8085:8085"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  export:
    build:
      context: ..
      dockerfile: docker/Dockerfile.maven
      args:
        SERVICE_DIR: export-service
    image: ops-export:latest
    env_file:
      - .env
    environment:
      - SERVER_PORT=8086
    ports:
      - "8086:8086"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8086/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

networks:
  default:
    name: ops_toptuna_net
